---
plugins:
  - import

parser: babel-eslint

env:
  node: true

extends:
  - 'airbnb-base'
  - eslint:recommended
  - plugin:import/errors
  - plugin:import/warnings

rules:
  import/no-unresolved: [2, {commonjs: true, amd: true}]
  import/named: 2
  import/namespace: 2
  import/default: 2
  import/export: 2
  no-console: 0